version: 2

models: 
  - name: dim_listings_cleansed # model name

    columns: 

    - name: listing_id # col name
      tests: 
        - unique
        - not_null
    
    - name: host_id # col name
      tests:
        - not_null
        - relationships: 
            to: ref('dim_hosts_cleansed') # note the indentation here has to be 4
            field: host_id
    
    - name: room_type # col name
      tests:
        - accepted_values:
            values: [ # note the indentation here has to be 4
              'Entire home/apt',
              'Private room',
              'Shared room',
              'Hotel room'
            ]
    
    - name: minimum_nights # col name
      tests:
        - positive_val
